language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - main
node_js:
  - 8
before_install:
  - npm i -g npm@^5.0.0
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - npm run report-coverage
